[package]
name = "rust-learning"
version = "0.1.0"
authors = ["max"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uint = "0.8"
termion = "1.5.5"
rand = "0.7.3"
