#!/bin/bash
set -eo pipefail
RUSTFLAGS="-L $PWD/libs" cargo build --release --target x86_64-pc-windows-gnu
rm -f target/windows/* target/windows.zip
mkdir -p target/windowstemp
cp target/x86_64-pc-windows-gnu/release/rust-learning.exe target/windowstemp
cp dlls/* target/windowstemp
zip -j target/windows.zip target/windowstemp/*
rm -rf target/windowstemp/
